# Generated by Django 4.0.3 on 2022-05-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
    ]
