# Generated by Django 4.0.3 on 2022-06-11 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0003_remove_machine_famille_remove_machine_mac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 9, 46, 52, 709116)),
        ),
    ]
