# Generated by Django 4.0.3 on 2022-06-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0013_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='maintenanceDate',
        ),
    ]
