# Generated by Django 4.0.3 on 2022-06-12 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0021_alter_machine_maintenancedate_alter_machine_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('PC', 'PC - Run windows'), ('Mac', 'Mac - Run MacOS'), ('Serveur', 'Serveur - Simple Serveur to deploy virtual machines'), ('Switch', 'Switch - To maintains and connect servers'), ('Routeur', 'Routeur - Use to have Internet')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 12, 9, 57, 37, 253777)),
        ),
    ]
