# Generated by Django 4.0.3 on 2022-06-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0026_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='switchs',
            name='maintenanceDate',
            field=models.DateField(),
        ),
    ]
