# Generated by Django 4.0.3 on 2022-06-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0027_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Switchs',
            new_name='Switch',
        ),
    ]
