# Generated by Django 4.0.3 on 2022-06-11 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0016_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 11, 17, 12, 43, 107039)),
        ),
    ]
