# Generated by Django 4.0.3 on 2022-06-12 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0023_routeur_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 12, 10, 35, 49, 991123)),
        ),
        migrations.AlterField(
            model_name='routeur',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 12, 10, 35, 50, 14064)),
        ),
    ]
