# Generated by Django 4.0.3 on 2022-06-12 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0025_switchs_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 12, 10, 41, 36, 659563)),
        ),
        migrations.AlterField(
            model_name='routeur',
            name='maintenanceDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='switchs',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 12, 10, 41, 36, 681959)),
        ),
    ]
