# Generated by Django 4.0.3 on 2022-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0028_rename_switchs_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=15)),
                ('maintenanceDate', models.DateField()),
                ('mach', models.CharField(choices=[('PC', 'PC - Run windows'), ('Mac', 'Mac - Run MacOS'), ('Serveur', 'Serveur - Simple Serveur to deploy virtual machines'), ('Switch', 'Switch - To maintains and connect servers'), ('Routeur', 'Routeur - Use to have Internet')], default='PC', max_length=32)),
            ],
        ),
    ]
